version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html:ro
    depends_on:
      - web
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
